version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./src
    command: bash setup.sh
    depends_on:
      - db
      - memcached
  memcached:
    image: memcached
    ports:
      - 11211:11211
    command: ["memcached"]

volumes:
  static-volume:
  media-volume:
  postgres_data:

