version: '3'

services:
  web:
    volumes:
      - static-volume:/src/static
      - media-volume:/src/media
    env_file:
      - web.env
      - db.env
    environment:
      - WEDDING_ENV=PRODUCTION
    depends_on:
      - db
      - memcached
    networks:
      web:
        aliases:
          - sophie_and_adam
      db:
  nginx:
    build: config/nginx/stage
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static-volume:/src/static
      - media-volume:/src/media
      - /etc/letsencrypt/.:/etc/letsencrypt
    networks:
      - web
    depends_on:
      - web
  db:
    env_file:
      - db.env
    networks:
      db:

volumes:
  static-volume:
  media-volume:
  app-volume:

networks:
  web:
  db: