# Generated by Django 2.1.5 on 2019-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190107_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='churchDistance',
            new_name='church_distance',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='receptionDistance',
            new_name='reception_distance',
        ),
    ]
