# Generated by Django 2.1.5 on 2019-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20190107_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
