# Generated by Django 2.1.5 on 2019-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='church_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reception_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='church_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reception_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
