# Generated by Django 2.1.5 on 2019-01-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='is_head',
            new_name='is_child',
        ),
    ]
