# Generated by Django 2.1.5 on 2019-01-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20190107_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invitee',
        ),
        migrations.AddField(
            model_name='guest',
            name='invitee',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='invite.Invite'),
            preserve_default=False,
        ),
    ]
