# Generated by Django 2.1.5 on 2019-01-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_auto_20190107_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='invitee',
        ),
    ]
