# Generated by Django 2.1.5 on 2019-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_remove_guest_invitee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='country',
        ),
        migrations.AddField(
            model_name='invite',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('DE', 'Germany')], default='UK', max_length=2),
        ),
    ]
