# Generated by Django 2.1.5 on 2019-01-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0006_auto_20190109_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='invite.Guest'),
        ),
    ]
