# Generated by Django 2.1.5 on 2019-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0007_auto_20190109_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
