# Generated by Django 2.1.5 on 2019-02-05 16:18

from django.db import migrations, models
from django.utils.text import slugify


def generate_slug(apps, schema_editor):
    Guest = apps.get_model('invite', 'Guest')
    for guest in Guest.objects.all():
        slug = slugify('{}{}{}'.format(
            guest.first_name[:3], guest.last_name[:3], guest.pk))
        guest.slug = slug
        guest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0008_response_message')
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='slug',
            field=models.CharField(
                max_length=200,
                null=True, blank=True, unique=False),
            preserve_default=False,
        ),
        migrations.RunPython(
            generate_slug,
        ),
        migrations.AlterField(
            model_name='guest',
            name='slug',
            field=models.SlugField(unique=True, editable=False),
            preserve_default=False,
        )
    ]
