# Generated by Django 2.1.5 on 2019-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0011_guest_is_message_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_message_sent',
        ),
        migrations.AddField(
            model_name='guest',
            name='message_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
