# Generated by Django 2.1.5 on 2019-05-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0012_auto_20190212_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='invite.Guest')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invite.Table')),
            ],
        ),
    ]
