# Generated by Django 2.1.5 on 2019-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0013_table_tableguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableguest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
